### ISSUE TITLE
iteration speed printout displayed at low verbosity.

### ISSUE THREAD

**Issue by Fraetor** [erdogant/findpeaks#10]
The printout `10000it [00:00, 46508.35it/s]` is displayed at any verbosity level greater than 0.

From the API reference, I would expect this only to print at `verbose=3` or higher.

**Comment by erdogant** [comment]
I fixed the verbosity messages in the new update. When verbose=0, nothing should be shown anymore. The progress bar is only shown if verbose>=4

`pip install -U findpeaks`

**Comment by Fraetor** [comment]
Can confirm as fixed.
