### ISSUE TITLE
Index error in findpeaks(method='caerus') using pandas 1.4.1

### ISSUE THREAD

**Issue by agumm** [erdogant/findpeaks#12]
X = np.sin(np.linspace(0,1,100))

from findpeaks import findpeaks
fp = findpeaks(method='caerus', params_caerus={'minperc': 5, 'window': 50})
results = fp.fit(X)

gives the following error
IndexError: index 100 is out of bounds for axis 0 with size 100

points to lines in caerus/utils/csutils.py
201             for k in range(0,len(results['loc_stop'][i])):
202                 df['labx'].iloc[np.arange(results['loc_stop'][i][k][0], results['loc_stop'][i][k][1])]=i+1

I'm using pandas version 1.4.1.

However,

from caerus import caerus

cs = caerus(window=50, threshold=0.5, minperc=10, nlargest=1)
cs.fit(modeldev.S.tdata['adjclose'].values, verbose=3)
cs.plot()

runs with no error with the same pandas

**Comment by erdogant** [comment]
Thanks for posting. I am going to look into this.

**Comment by erdogant** [comment]
I fixed the issue. There were some nan values that were not removed from the index.
Update with `pip install -U findpeaks`. It should work now.

**Comment by erdogant** [comment]
Re-open if you still experience issues regarding this issue.
