### ISSUE TITLE
Logging printing with verbose = 0

### ISSUE THREAD

**Issue by gothery** [erdogant/findpeaks#13]
When calling 
findpeaks.findpeaks(method='mask', verbose=0) 
logging still outputs because the call in findpeaks.peaks2d for mask is 
result = stats.mask(Xproc, limit=self.limit)

The function stats.mask is defined as
def mask(X, limit=0, verbose=3):
and has 
if verbose>=3: print('[findpeaks] >Detect peaks using the mask method with limit=%s.' %(limit))

Since the verbose input isn't passed to mask than the output still prints.

Please update the function call to 
result = stats.mask(Xproc, limit=self.limit, verbose=self.verbose)

Thanks.

**Comment by erdogant** [comment]
Thanks for notifying me. I fixed the issue.
Update to the latest version using:

`pip install -U findpeaks
`

**Comment by gothery** [comment]
Thanks!
