### ISSUE TITLE
How detect the TOPs?

### ISSUE THREAD

**Issue by 9kwon** [erdogant/findpeaks#14]
Hi, 
Thank you first for your great library.
I am trying to simmulate it with the documents.
The problem is there are BOTTOM detections on the graph.
I used my data instread of yours and other is the same on the document.
Please let me know how to adjust them.

![image](https://user-images.githubusercontent.com/25417906/195529278-07f42680-45b4-41b4-8707-8598e6efc5ab.png)

**Comment by erdogant** [comment]
Good point. In the plot, the whitelisting did not work. I now only plot what is whitelisted. 
Does this solve your issue?

```
from findpeaks import findpeaks
X = [1,1,1.1,1,0.9,1,1,1.1,1,0.9,1,1.1,1,1,0.9,1,1,1.1,1,1,1,1,1.1,0.9,1,1.1,1,1,0.9,1,1.1,1,1,1.1,1,0.8,0.9,1,1.2,0.9,1,1,1.1,1.2,1,1.5,1,3,2,5,3,2,1,1,1,0.9,1,1,3,2.6,4,3,3.2,2,1,1,0.8,4,4,2,2.5,1,1,1]

fp = findpeaks(method='peakdetect', lookahead=1, verbose=3, whitelist=['peak'])
results = fp.fit(X)
fp.plot(xlabel='x-axis', ylabel='y-axis')
```
