### ISSUE TITLE
To limit the distance between adjacent peak and valley points when finding peak & valley points 

### ISSUE THREAD

**Issue by rose-jinyang** [erdogant/findpeaks#15]
Hello
How are you?
Thanks for contributing to this project.
Does this repo support to limit the distance between adjacent peak and valley points when finding peak & valley points?

![image](https://user-images.githubusercontent.com/47862419/211860839-a648e6a5-9555-4561-9716-880b76555f8e.png)

As u can see in the above figure, the distance between the first peak and valley points is very small and I want to ignore these points.

**Comment by erdogant** [comment]
I understand your point but how would you then decide which point to take when combining multiple points?

**Comment by mmarras** [comment]
Can't you discriminate based on `"score"` values? should be low for those fellas in the top left. Aka in the island/watershed speak those island disappear quickly when raising the water level.

**Comment by erdogant** [comment]
This should be possible with the birth/death levels. See[Documentation ](https://erdogant.github.io/findpeaks/pages/html/Topology.html) that describes the topology method in more depth. Is this what you mean?

**Comment by erdogant** [comment]
Closing this one. Let me know if it is still an issue.
