### ISSUE TITLE
caerus crash error

### ISSUE THREAD

**Issue by allran** [erdogant/findpeaks#17]
The last version of caerus==0.1.8
At file path 'https://github.com/erdogant/caerus/tree/master/caerus/utils)/csplots.py`, the function name is `def _plot_graph(out, figsize=(15,8)):`
But your code in `findpeaks.py` is:`csplots._plot_graph(self.results['model'].results, figsize=self.figsize, xlabel=xlabel, ylabel=ylabel)`
Then, will get follow error code: `TypeError: _plot_graph() got an unexpected keyword argument 'xlabel'`.

Please remove the xlabel and ylabel to fix it.

**Comment by erdogant** [comment]
I fixed the error. please update to the latest version with `pip install -U findpeaks`
