### ISSUE TITLE
Limiting z axis in plot_mesh

### ISSUE THREAD

**Issue by nrthIxne** [erdogant/findpeaks#18]
This is perhaps an easy/stupid question, but how to I limit the z-axis. I have transmission images, ranging between 0 and 1 on the z-axis. When using:

```
fp = findpeaks.findpeaks(method='topology', scale=False, denoise=None, togray=False, imsize=False, window=15)
fp.fit(transmission)
fp.plot_mesh(wireframe=False, title='Test', cmap='RdBu', view=(70,5))
```

I run into the issue that my z-axis goes from -5000 to 15000 and thus everything looks the same. Thank you for your help and the awesome tool!

**Comment by erdogant** [comment]
I added this functionality!
Update to the latest version with:

`pip install -U findpeaks
`
See [here](https://erdogant.github.io/findpeaks/pages/html/findpeaks.findpeaks.html#findpeaks.findpeaks.findpeaks.plot_mesh) for the documentation.

Example without limit
![image](https://github.com/erdogant/findpeaks/assets/31008129/45d483b6-7a6d-4b35-acef-ebf71eb3ec28)

With limit on x-axis and y-axis
![image](https://github.com/erdogant/findpeaks/assets/31008129/659e60dd-d9f6-48d0-ab89-07e5ff686a42)

With limit on x-axis and y-axis and z-axis
![image](https://github.com/erdogant/findpeaks/assets/31008129/b6f9a1d5-d1f8-4b99-8558-d99ec8602db9)


In case you want to show your gratitude, this library runs on coffee ;)

<a href='https://www.buymeacoffee.com/erdogant' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi1.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
