### ISSUE TITLE
Feature request - Multiplicative Noise Lee Despeckling Filter

### ISSUE THREAD

**Issue by masawdah** [erdogant/findpeaks#19]
We would like to propose the implementation of the Multiplicative Noise Lee Despeckling Filter as a new feature. Multiplicative noise is commonly encountered in SAR images, particularly in Sentinel-1 satellite data. It is crucial to address this noise during the pre-processing stage. Currently, popular software such as SNAP and ArcGIS offer the Multiplicative Noise Lee Despeckling Filter, but we haven't found an open-source Python implementation available for integration into our preprocessing pipeline. Hence, we aim to contribute to this package by adding the filter and making it accessible to the wider community. 

We would like to hear from you what do you think for this contribution.

**Comment by carolinegoehner** [comment]
In detail, in python we implemented the "Lee Sigma" filter from [1] that is used by SNAP. We achieved comparable results to the java based implementation. As we could not find any other python code for this filter, we would be happy to contribute this as it fits very well to the other Lee filters documented in findpeaks.

[1] Jong-Sen Lee, Jen-Hung Wen, T. L. Ainsworth, Kun-Shan Chen and A. J. Chen, "Improved Sigma Filter for Speckle Filtering of SAR Imagery", in IEEE Transactions on Geoscience and Remote Sensing, vol. 47, no. 1, pp. 202-213, Jan. 2009, doi: 10.1109/TGRS.2008.2002881.

**Comment by carolinegoehner** [comment]
Perfect, thank you very much! We now cloned your repository and would implement the filter similar to the ones already present. After checking and testing also with the sample image provided by you, we can do a pull request. Is that fine for you?

**Comment by erdogant** [comment]
yes thats fine. Looking forward to it!

**Comment by erdogant** [comment]
Thank you! Closing this one!
