### ISSUE TITLE
Plot Doesn't Display?

### ISSUE THREAD

**Issue by windowshopr** [erdogant/findpeaks#2]
The below code works without error, however the plot command doesn't do anything; no plot appears or saves anywhere and the script just ends. It gives a `A value is trying to be set on a copy of a slice from a DataFrame` warning for some reason, even though I'm feeding it a list? I have the latest matplotlib version, running on Windows 10, Python 3.6.

Code

```
# Load library
from findpeaks import findpeaks
# Data
X = [10,11,9,23,21,11,45,20,11,12]
# Initialize
fp = findpeaks(method='peakdetect', lookahead=1)
results = fp.fit(X)
# Plot
fp.plot()
```

Output

```
[findpeaks] >Finding peaks in 1d-vector using [peakdetect] method..
C:\...\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

C:\Users\...>
```

**Comment by erdogant** [comment]
Thank you for mentioning this!
I released a fix. Update with:

`pip install -U findpeaks
`
