### ISSUE TITLE
pip installation does not include joblib

### ISSUE THREAD

**Issue by squaregoldfish** [erdogant/findpeaks#24]
Installing findpeaks through pip doesn't set up the required joblib package.

I know very little of pip stuff, but it looks like the package is missing from `setup.py` (it's in `requirements.txt`).

**Comment by erdogant** [comment]
thanks for the message! I added it to the setup file.

**Comment by erdogant** [comment]
The fix is available from version 2.5.3.
Update to the latest version with
`pip install -U findpeaks
`
