### ISSUE TITLE
Add `delta` parameter for peakdetect

### ISSUE THREAD

**Issue by subhacom** [erdogant/findpeaks#25]
Currently there appears to be no way to pass the `delta` parameter to the peakdetect algorithm (which is implemented in [@sixtenbe](https://gist.github.com/sixtenbe/1178136) 's code). So `findpeaks(method='peakdetect')` seems to use the default `delta=0`.
Adding a keyword argument to `findpeaks` to allow passing the `delta` parameter to `peakdetect` will give more flexibility.

**Comment by erdogant** [comment]
Great suggestion. I incorporated it into findpeaks.
Update to the latest version with `pip install -U findpeaks`

```
from findpeaks import findpeaks
fp = findpeaks(method='peakdetect', params={'delta': 1})

```
