### ISSUE TITLE
Removing output messages during runtime

### ISSUE THREAD

**Issue by matthewkuner** [erdogant/findpeaks#3]
Currently, even while using the `verbose = 0` option on findpeaks, I still regularly get outputs that look something like `65536it [00:01, 48554.31it/s]` when running. 

For added context, the exact line I am running is:
`fp = findpeaks(method='topology', 
                       scale=False, 
                       denoise = None,
                       togray = False,
                       verbose = 0)`
and this is being ran on Windows 10 using Python 3.7.3.

Is there a way to remove this?

**Comment by erdogant** [comment]
Thank you for your issue!

I fixed the issue. can you check it by updating the library?

`pip install -U findpeaks
`

**Comment by matthewkuner** [comment]
Hi @erdogant, I tried running `pip install -U findpeaks`, but it simply said all of the packages were up to date. Does it usually take a bit for PyPi/pip to distribute an updated version of a package?

**Comment by erdogant** [comment]
Should be fixed now

**Comment by matthewkuner** [comment]
It works great now! Thank you so much for your active support.
