### ISSUE TITLE
facebook stock example not working (caerus.__init__() got an unexpected keyword argument 'delta')

### ISSUE THREAD

**Issue by SubhranshuSharma** [erdogant/findpeaks#32]
the [facebook stock example](https://erdogant.github.io/findpeaks/pages/html/Use-cases.html#facebook-stocks) isnt working and giving [error](https://pastebin.com/yLGMdLzs), seems to be originating from `fp.fit(X)`
edit: it can be fixed by adding `params={'minperc':10}` in `findpeaks`, update the documentation

**Comment by erdogant** [comment]
Thank you. I fixed this issue. Update to the latest version with `pip install -U findpeaks`
