### ISSUE TITLE
Incorrect classification for low-variance data

### ISSUE THREAD

**Issue by kohlert** [erdogant/findpeaks#35]
I often work with timeseries data in log space, and it can have a fairly small absolute variance.  I believe the fix for [issue #26](https://github.com/erdogant/findpeaks/issues/26) has since caused another bug where the added random noise (up to 0.1, based on the distribution used) can be sufficient to introduce significant errors into the resulting peak detection.

![image](https://github.com/user-attachments/assets/b8fc26d2-7051-4794-a44c-43887d1ab6ea)

The ideal solution would probably be to use indexing instead of relying on unique values for de-duplication, but that might require some additional refactoring that I haven't fully scoped out.

A simple alternative solution could be to use the smallest available increment to de-duplicate the data instead of relying on random noise.

**Comment by erdogant** [comment]
Thank you for this contribution! Your solution is much better than adding random noise. I created a new version.

**Comment by kohlert** [comment]
Glad I could help out.  Thanks for all the work you do on the library.  This is a great resource!
