### ISSUE TITLE
data-dependent issues with interpolate

### ISSUE THREAD

**Issue by davedgd** [erdogant/findpeaks#4]
@erdogant: thanks for the great package!

I've encountered a small issue where interpolate causes problems that depend on the input data. Here's a small reproducible example using numpy:

```python
import numpy as np
from findpeaks import findpeaks

np.random.seed(200)
peakDat = np.random.randint(200, size = 400)

fp = findpeaks(method = 'topology',
               interpolate = 10, 
               lookahead = 1)

results = fp.fit(peakDat)
```

This produces the following error: `ValueError: cannot set using a list-like indexer with a different length than the value`

By contrast, a different seed works fine with these arguments:

```python
import numpy as np
from findpeaks import findpeaks

np.random.seed(100)
peakDat = np.random.randint(200, size = 400)

fp = findpeaks(method = 'topology',
               interpolate = 10, 
               lookahead = 1)

results = fp.fit(peakDat)
```

Changing the `interpolate` factor from 10 can fix the issue for a given data set, but it's unclear from the documentation if there's a better way to avoid having to tweak the settings at the data-set level.

**Comment by erdogant** [comment]
I fixed the bug which happened in case a peak is detected twice which can happen when using random data. A loc statement returns unique events and is now changed into iloc which solves the bug. 

Update as below and give it a try!

`pip install -U findpeaks
`

**Comment by davedgd** [comment]
Hi @erdogant: thanks for the amazingly quick reply! This does appear to resolve the issue -- I really appreciate it. =)
