### ISSUE TITLE
findpeaks.fit applied to 2D data returns wrong coordinates

### ISSUE THREAD

**Issue by martijnende** [erdogant/findpeaks#5]
Hi and thanks for developing this project. I want to get the peaks in my data using persistent topology, but the resulting dictionary contains the wrong coordinates for the peak locations. Consider the following minimal example:

```
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter

from findpeaks import findpeaks

rng = np.random.default_rng(42)

x = rng.normal(size=(50, 50))
x = gaussian_filter(x, sigma=10.)
x -= x.min()
x = 255 * x / x.max()

fp = findpeaks(method="topology", denoise=None, verbose=0)
results = fp.fit(x)

plt.close("all")
plt.figure(constrained_layout=True)
plt.imshow(x, aspect="auto", cmap="coolwarm", interpolation="none", vmin=0, vmax=255)
plt.axis("off")
plt.show()
```
![download](https://user-images.githubusercontent.com/6959003/126911547-89bdda17-4d11-49fd-977d-1be0433d5cfd.png)

The global maximum of the data is at `(0, 21)` (i.e., top row, about half-way from the left). But when I print `results["persistence"]`, I get:

```
    x    y  birth_level  death_level  score
0   0  255          255            0    255
1  49  182          182           88     94
2  14  253          253          211     42
3   0  212          212          212      0
```

If I understood things correctly, `y` should denote the y-coordinate in pixel-space, but it seems to just be a copy of `birth_level`, which is the value at the pixel where the peak is located.

Is this a bug, or did I do something wrong?

**Comment by erdogant** [comment]
Thank you for mentioning this!
I fixed this issue and released a new version.

Update with:

pip install -U findpeaks

from findpeaks import findpeaks
fp = findpeaks(method="topology", denoise=None, limit=0)
results = fp.fit(x)

results['persistence']

    x   y  birth_level  death_level  score
0  21   0          255            0    255
1  41  49          182           88     94
2   0  14          253          211     42

# Plot detected peaks in imshow
plt.imshow(fp.results['Xdetect'], cmap='gray_r')

# Make plot with:
fp.plot(cmap='coolwarm')

# Make persistence plot with: 
fp.plot_persistence()

```

**Comment by martijnende** [comment]
Perfect, thanks!
