### ISSUE TITLE
Ascending/Descending Manifold

### ISSUE THREAD

**Issue by ollielo** [erdogant/findpeaks#7]
Currently the `result['df']['labx']` labels the ascending manifold in the Morse-Smale complex. The `labx` should be rename to its technical term.

Since the implementation goes through the data both top-down and bottom-up, labeling of descending manifold should be supported as well.

**Comment by ollielo** [comment]
The "labx" marks the mountain for each peak as in the [plot](https://github.com/erdogant/findpeaks/blob/master/docs/figs/fig1_interpol.png). I want the *opposite* of "labx" that marks the *valley* or *basin* of each "trough". This helps with answering the question, *when it rains, which valley will be flooded?* Turn the plot up side down and you will understand.

**Comment by erdogant** [comment]
The _**labx**_ values are the labels for input **_x_** and represent the regions that belongs to a "peak" or "valley".
The exact peak and valleys are stored in "valley" and "peak".

Small example:

```
from findpeaks import findpeaks
# Data
X = [10,11,9,23,21,11,45,20,11,12]
# Initialize
fp = findpeaks(method='topology', lookahead=1)
results = fp.fit(X)
fp.plot()
results['df']
```

![image](https://user-images.githubusercontent.com/31008129/144605668-f47f13b8-d388-4486-ba8e-a3cb15072cc5.png)

`print(results['df'])`

The first valley=True start at (x,y)=(0,0) until the coordinates (2,9). The region that covers that region is stored in labx and is the same value.

```
   x   y  labx  rank  score  valley   peak
0  0  10   1.0     0    0.0    True  False
1  1  11   1.0     3    2.0   False   True
2  2   9   2.0     0    0.0    True  False
3  3  23   2.0     2   12.0   False   True
4  4  21   2.0     0    0.0   False  False
5  5  11   3.0     0    0.0    True  False
6  6  45   3.0     1   45.0   False   True
7  7  20   3.0     0    0.0   False  False
8  8  11   4.0     0    0.0    True  False
9  9  12   4.0     4    1.0    True   True

```
