### ISSUE TITLE
Citation improvement

### ISSUE THREAD

**Issue by pintergreg** [erdogant/findpeaks#8]
Hey @erdogant ,

I've just found this lib and still experimenting with it, but let me suggest two other ways for the citation.

1. Zenodo; it provides a DOI for every version, better citation entry in multiple format, tracks the papers that uses your code and it's free
     - see SciPy's record https://zenodo.org/record/5725464
2. Add CITATION.cff to the repo; it's a nice [GitHub feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

Regards,

**Comment by erdogant** [comment]
Thank you for the suggestion! I did both!
