### ISSUE TITLE
Resizing info displayed on verbosity < 3.

### ISSUE THREAD

**Issue by Fraetor** [erdogant/findpeaks#9]
Running findpeaks with `verbose=0` still prints out `[findpeaks] >Resizing image to (100, 100).`

I would expect this information not to be displayed below `verbose=3`.

**Comment by erdogant** [comment]
I fixed the verbosity messages in the new update. When verbose=0, nothing should be shown anymore. The progress bar is only shown if verbose>=4

`pip install -U findpeaks`

**Comment by Fraetor** [comment]
Can confirm as fixed.
